name: emergency-response
version: "1.0"
description: Fast-track workflow for critical severity anomalies requiring immediate action

triggers:
  - event: anomaly.critical
    condition: severity == 'critical'

config:
  timeout: 1800 # 30 minutes
  priority: high
  parallel_execution: true

steps:
  - id: immediate_assessment
    name: Immediate Assessment
    type: action
    action: rapid_ai_analysis
    timeout: 30
    config:
      model: gemini-1.5-pro
      priority: high
      quick_mode: true
    next: parallel_actions

  - id: parallel_actions
    name: Parallel Emergency Actions
    type: parallel
    branches:
      - id: notify_stakeholders
        steps:
          - id: alert_team
            name: Alert Response Team
            type: action
            action: send_emergency_alert
            config:
              channels:
                - websocket
                - sms
                - email
              priority: critical
              
      - id: gather_intel
        steps:
          - id: collect_data
            name: Collect Additional Data
            type: action
            action: gather_emergency_data
            config:
              sources:
                - satellite
                - sensors
                - social_media
                
      - id: impact_analysis
        steps:
          - id: assess_impact
            name: Assess Impact
            type: action
            action: calculate_impact
            config:
              include_population: true
              include_infrastructure: true
              
    next: escalation_decision

  - id: escalation_decision
    name: Escalation Decision
    type: gateway
    gateway_type: exclusive
    conditions:
      - expression: "${impact_score >= 0.9}"
        next: full_escalation
      - expression: "${impact_score >= 0.7}"
        next: partial_escalation
      - expression: "true"
        next: standard_response

  - id: full_escalation
    name: Full Escalation
    type: action
    action: escalate_to_authorities
    config:
      agencies:
        - emergency_services
        - government
        - media
      auto_approve: true
    next: monitor

  - id: partial_escalation
    name: Partial Escalation
    type: action
    action: escalate_to_team
    config:
      require_confirmation: true
    next: monitor

  - id: standard_response
    name: Standard Response
    type: action
    action: standard_response_protocol
    next: monitor

  - id: monitor
    name: Continuous Monitoring
    type: action
    action: setup_monitoring
    config:
      duration: 86400 # 24 hours
      update_interval: 300 # 5 minutes
    next: end

  - id: end
    name: Emergency Response Complete
    type: end
    config:
      generate_report: true
      archive_data: true
